name: Java CI Build

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Maven cache
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Clean Workspace
        working-directory: ./TourGuide
        run: mvn clean

      - name: Compile
        if: success()
        working-directory: ./TourGuide
        run: mvn compile

      - name: Run Tests
        if: success()
        working-directory: ./TourGuide
        run: mvn test

      - name: Build Package
        if: success()
        working-directory: ./TourGuide
        run: mvn package -DskipTests

      - name: Upload artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: TourGuide-JAR
          path: ./TourGuide/target/*.jar

      - name: Generate JaCoCo Report
        working-directory: ./TourGuide
        run: mvn jacoco:report

      - name: Deploy JaCoCo Report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./TourGuide/target/site/jacoco
